In [38]:
import numpy
import os

coordinate_file = os.path.join('data', 'water.xyz')

coordinates = numpy.genfromtxt(fname=coordinate_file, skip_header=2, dtype='unicode')

atom = coordinates[:,0]
data = coordinates[:,1:]


data = data.astype(numpy.float)
print(data)

#distance = []
#for atom1 in range(0,len(data)):
#    x1 = coordinates[atom1, 1]
#    print(x1)
#    y1 = coordinates[atom1, 2]
#    z1 = coordinates[atom1, 3]
    
#    for atom2 in range(0,len(data)):
#         x2 = coordinates[atom2, 1]
#         y2 = coordinates[atom2, 2]
#         z2 = coordinates[atom2, 3]   
#         distancecalc = numpy.sqrt((x1-x2)**2 + (y1-y2)**2 + (z1 - z2)**2)
#         print(distancecalc)
   #      distance.append(distancecalc)





[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [20]:
len(data)

3

In [24]:
data


array([[ 0.      , -0.007156,  0.965491],
       [-0.      ,  0.001486, -0.003471],
       [ 0.      ,  0.931026,  1.207929]])

In [25]:
distancecalc = numpy.sqrt((x1-x2)**2 + (y1-y2)**2 + (z1 - z2)**2)

TypeError: unsupported operand type(s) for -: 'numpy.str_' and 'numpy.str_'

In [26]:
x1-x2


TypeError: unsupported operand type(s) for -: 'numpy.str_' and 'numpy.str_'

In [27]:
type(data)

numpy.ndarray

In [28]:
x1


'0.000000'

In [29]:
x2

'0.000000'

In [30]:
type(coordinatesupdate)


numpy.ndarray

In [36]:
test=data.astype(numpy.float)

In [37]:
type(test)

numpy.ndarray

In [39]:
data[0,0] + data[1,1]

0.001486

In [55]:
import os

coordinate_file = os.path.join('data', 'water.xyz')

coordinates = numpy.genfromtxt(fname=coordinate_file, skip_header=2, dtype='unicode')

atom = coordinates[:,0]
data = coordinates[:,1:]


data = data.astype(numpy.float)


distance = []
for atom1 in range(0,len(data)):
    x1 = data[atom1, 0]
    y1 = data[atom1, 1]
    z1 = data[atom1, 2]
    atom1name = atom[atom1]
    for atom2 in range(0,len(data)):
         x2 = data[atom2, 0]
         y2 = data[atom2, 1]
         z2 = data[atom2, 2]
         atom2name = atom[atom2]
         distancecalc = numpy.sqrt((x1-x2)**2 + (y1-y2)**2 + (z1 - z2)**2)
         print(F'{atom1name[atom1]}')

O
O
O
1
1
1


IndexError: string index out of range

In [43]:
coordinates(0,0)

TypeError: 'numpy.ndarray' object is not callable

## one solution
import numpy
import os

coordinate_file = os.path.join('data', 'water.xyz')

coordinates = numpy.genfromtxt(fname=coordinate_file, skip_header=2, dtype='unicode')

atom = coordinates[:,0]
data = coordinates[:,1:]


data = data.astype(numpy.float)


distance = []
for atom1 in range(0,len(data)):
    x1 = data[atom1, 0]
    y1 = data[atom1, 1]
    z1 = data[atom1, 2]
    atom1name = atom[atom1]
    for atom2 in range(0,len(data)):
         x2 = data[atom2, 0]
         y2 = data[atom2, 1]
         z2 = data[atom2, 2]
         atom2name = atom[atom2]
         distancecalc = numpy.sqrt((x1-x2)**2 + (y1-y2)**2 + (z1 - z2)**2)
         print(F'{atom1name} to {atom2name} : {distancecalc: .3F}')

In [76]:
## ANOTHER SOLUTION
import numpy
import os

coordinate_file = os.path.join('data', 'water.xyz')

coordinates = numpy.genfromtxt(fname=coordinate_file, skip_header=2, dtype='unicode')

atom = coordinates[:,0]
data = coordinates[:,1:]


data = data.astype(numpy.float)
num_atoms = len(atom)

distance = []
for atom1 in range(0,num_atoms):
    for atom2 in range(0, num_atoms):
        x_distance = data[atom1, 0] - data[atom2, 0]
        y_distance = data[atom1, 1] - data[atom2, 1]
        z_distance = data[atom1, 2] - data[atom2, 2]
        bondlength = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        print(F'{atom[atom1]} to {atom[atom2]} : {bondlength : .3F}')

O to O :  0.000
O to H1 :  0.969
O to H2 :  0.969
H1 to O :  0.969
H1 to H1 :  0.000
H1 to H2 :  1.527
H2 to O :  0.969
H2 to H1 :  1.527
H2 to H2 :  0.000


In [77]:
## ELIMINATE ANYTHING THAT IS NOT A BOND
## ANOTHER SOLUTION
import numpy
import os

coordinate_file = os.path.join('data', 'water.xyz')

coordinates = numpy.genfromtxt(fname=coordinate_file, skip_header=2, dtype='unicode')

atom = coordinates[:,0]
data = coordinates[:,1:]


data = data.astype(numpy.float)
num_atoms = len(atom)

distance = []
for atom1 in range(0,num_atoms):
    for atom2 in range(0, num_atoms):
        x_distance = data[atom1, 0] - data[atom2, 0]
        y_distance = data[atom1, 1] - data[atom2, 1]
        z_distance = data[atom1, 2] - data[atom2, 2]
        bondlength_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        if bondlength_12 > 0 and bondlength_12 < 1.5:
            print(F'{atom[atom1]} to {atom[atom2]} : {bondlength_12 : .3F}')

O to H1 :  0.969
O to H2 :  0.969
H1 to O :  0.969
H2 to O :  0.969


In [78]:
## ELIMINATE DUPLICATES
import numpy
import os

coordinate_file = os.path.join('data', 'water.xyz')

coordinates = numpy.genfromtxt(fname=coordinate_file, skip_header=2, dtype='unicode')

atom = coordinates[:,0]
data = coordinates[:,1:]


data = data.astype(numpy.float)
num_atoms = len(atom)


for atom1 in range(0,num_atoms):
    for atom2 in range(0, num_atoms):
        if atom1 < atom2:
            x_distance = data[atom1, 0] - data[atom2, 0]
            y_distance = data[atom1, 1] - data[atom2, 1]
            z_distance = data[atom1, 2] - data[atom2, 2]
            bondlength_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if bondlength_12 > 0 and bondlength_12 < 1.5:
                print(F'{atom[atom1]} to {atom[atom2]} : {bondlength_12 : .3F}')

O to H1 :  0.969
O to H2 :  0.969


In [79]:
## def function_name(parameters):
##     function code goes here
##     this could be multiple lines
##     return value_to_return


In [ ]:
def calculate_distance(atom1_coord, atom2_coord):
    """This function takes the coordinates of two atoms and calculates the distances between them.
    Input: atom1_coord, atom2_coord
    Returns: distance
    """
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance


In [82]:
num_atoms = len(atom)


for atom1 in range(0,num_atoms):
    for atom2 in range(0, num_atoms):
        if atom1 < atom2:
            bondlength_12 = calculate_distance(data[atom1], data[atom2])
            if bondlength_12 > 0 and bondlength_12 < 1.5:
                print(F'{atom[atom1]} to {atom[atom2]} : {bondlength_12 : .3F}')

O to H1 :  0.969
O to H2 :  0.969


In [ ]:
help()


Welcome to Python 3.6's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.6/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".



In [ ]:
help(calculate_distance)


In [ ]:
def calculate_distance(atom1_coord, atom2_coord):
    """This function takes the coordinates of two atoms and calculates the distances between them.
    Input: atom1_coord, atom2_coord
    Returns: distance
    """
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [ ]:
help(calculate_distance)

In [ ]:
# Write a new function called bond_check. Check and see if a distance is between 0 and 1.5 
# Angstroms. Return true or false
def bond_check(distance):
    """
    This function checks if the distance is between 0 and 1.5 Angstroms
    Input: distance 
    Returns: True or False
    
    """
    if distance > 0 and distance < 1.5:
        return True
    else:
        return False

In [ ]:
help(bond_check)

In [ ]:
bond_check(9)

In [ ]:
def bond_check(distance):
    """
    This function checks if the distance is between 0 and 1.5 Angstroms
    Input: distance 
    Returns: True or False
    
    """
    if distance > 0 and distance < 1.5:
        return True
    else:
        return False

In [ ]:
6+8
